// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE55FqsjXBGRrDxq-JPflSon1qTLOX9fc',
    appId: '1:682281095463:web:4e9533c1c30e6919e55902',
    messagingSenderId: '682281095463',
    projectId: 'fruit-hub-99ac9',
    authDomain: 'fruit-hub-99ac9.firebaseapp.com',
    storageBucket: 'fruit-hub-99ac9.firebasestorage.app',
    measurementId: 'G-QRRZWVJLB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAleWTWqAhcoDdzO5UGsxVXLCE7iJg9JC8',
    appId: '1:682281095463:android:66b418fbd015c9bae55902',
    messagingSenderId: '682281095463',
    projectId: 'fruit-hub-99ac9',
    storageBucket: 'fruit-hub-99ac9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvGfyBI-hSTKmyYD9NKGS6y08xlxeHKeg',
    appId: '1:682281095463:ios:70aef3ffe6ae30fae55902',
    messagingSenderId: '682281095463',
    projectId: 'fruit-hub-99ac9',
    storageBucket: 'fruit-hub-99ac9.firebasestorage.app',
    androidClientId: '682281095463-9vk70c616rk9rsjspo2jic495jcvevgn.apps.googleusercontent.com',
    iosClientId: '682281095463-0msg1fu08atvoum3aece8mbfdhd44dih.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvGfyBI-hSTKmyYD9NKGS6y08xlxeHKeg',
    appId: '1:682281095463:ios:70aef3ffe6ae30fae55902',
    messagingSenderId: '682281095463',
    projectId: 'fruit-hub-99ac9',
    storageBucket: 'fruit-hub-99ac9.firebasestorage.app',
    androidClientId: '682281095463-9vk70c616rk9rsjspo2jic495jcvevgn.apps.googleusercontent.com',
    iosClientId: '682281095463-0msg1fu08atvoum3aece8mbfdhd44dih.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE55FqsjXBGRrDxq-JPflSon1qTLOX9fc',
    appId: '1:682281095463:web:7b6dfee50e29e646e55902',
    messagingSenderId: '682281095463',
    projectId: 'fruit-hub-99ac9',
    authDomain: 'fruit-hub-99ac9.firebaseapp.com',
    storageBucket: 'fruit-hub-99ac9.firebasestorage.app',
    measurementId: 'G-8WH05M7SMW',
  );
}
